services:
  - type: web
    name: jess-ai
    runtime: docker  # Force Render to use Docker instead of Python buildpack
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jessai-db
          property: connectionString
    plan: free

databases:
  - name: jessai-db
    plan: free
    databaseName: jessai
    user: jessai
